package app.estat.mob.db.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import app.estat.mob.db.converter.BookConverter;
import app.estat.mob.db.entity.Sire;
import app.estat.mob.db.type.Book;

import app.estat.mob.db.entity.Cow;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COW".
*/
public class CowDao extends AbstractDao<Cow, Long> {

    public static final String TABLENAME = "COW";

    /**
     * Properties of entity Cow.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Number = new Property(2, String.class, "number", false, "NUMBER");
        public final static Property Book = new Property(3, String.class, "book", false, "BOOK");
        public final static Property SireId = new Property(4, Long.class, "sireId", false, "SIRE_ID");
        public final static Property Birthday = new Property(5, java.util.Date.class, "birthday", false, "BIRTHDAY");
    }

    private DaoSession daoSession;

    private final BookConverter bookConverter = new BookConverter();
    private Query<Cow> sire_ChildrenQuery;

    public CowDao(DaoConfig config) {
        super(config);
    }
    
    public CowDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COW\" (" + //
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"NUMBER\" TEXT," + // 2: number
                "\"BOOK\" TEXT," + // 3: book
                "\"SIRE_ID\" INTEGER," + // 4: sireId
                "\"BIRTHDAY\" INTEGER);"); // 5: birthday
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COW\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Cow entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(3, number);
        }
 
        Book book = entity.getBook();
        if (book != null) {
            stmt.bindString(4, bookConverter.convertToDatabaseValue(book));
        }
 
        Long sireId = entity.getSireId();
        if (sireId != null) {
            stmt.bindLong(5, sireId);
        }
 
        java.util.Date birthday = entity.getBirthday();
        if (birthday != null) {
            stmt.bindLong(6, birthday.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Cow entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(3, number);
        }
 
        Book book = entity.getBook();
        if (book != null) {
            stmt.bindString(4, bookConverter.convertToDatabaseValue(book));
        }
 
        Long sireId = entity.getSireId();
        if (sireId != null) {
            stmt.bindLong(5, sireId);
        }
 
        java.util.Date birthday = entity.getBirthday();
        if (birthday != null) {
            stmt.bindLong(6, birthday.getTime());
        }
    }

    @Override
    protected final void attachEntity(Cow entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Cow readEntity(Cursor cursor, int offset) {
        Cow entity = new Cow( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // number
            cursor.isNull(offset + 3) ? null : bookConverter.convertToEntityProperty(cursor.getString(offset + 3)), // book
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // sireId
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)) // birthday
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Cow entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNumber(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBook(cursor.isNull(offset + 3) ? null : bookConverter.convertToEntityProperty(cursor.getString(offset + 3)));
        entity.setSireId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setBirthday(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Cow entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Cow entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Cow entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "children" to-many relationship of Sire. */
    public List<Cow> _querySire_Children(Long id) {
        synchronized (this) {
            if (sire_ChildrenQuery == null) {
                QueryBuilder<Cow> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Id.eq(null));
                sire_ChildrenQuery = queryBuilder.build();
            }
        }
        Query<Cow> query = sire_ChildrenQuery.forCurrentThread();
        query.setParameter(0, id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSireDao().getAllColumns());
            builder.append(" FROM COW T");
            builder.append(" LEFT JOIN SIRE T0 ON T.\"SIRE_ID\"=T0.\"ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Cow loadCurrentDeep(Cursor cursor, boolean lock) {
        Cow entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Sire sire = loadCurrentOther(daoSession.getSireDao(), cursor, offset);
        entity.setSire(sire);

        return entity;    
    }

    public Cow loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Cow> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Cow> list = new ArrayList<Cow>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Cow> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Cow> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
