package app.estat.mob.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import app.estat.mob.db.entity.Cow;
import app.estat.mob.db.entity.CowParent;

import app.estat.mob.db.dao.CowDao;
import app.estat.mob.db.dao.CowParentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cowDaoConfig;
    private final DaoConfig cowParentDaoConfig;

    private final CowDao cowDao;
    private final CowParentDao cowParentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cowDaoConfig = daoConfigMap.get(CowDao.class).clone();
        cowDaoConfig.initIdentityScope(type);

        cowParentDaoConfig = daoConfigMap.get(CowParentDao.class).clone();
        cowParentDaoConfig.initIdentityScope(type);

        cowDao = new CowDao(cowDaoConfig, this);
        cowParentDao = new CowParentDao(cowParentDaoConfig, this);

        registerDao(Cow.class, cowDao);
        registerDao(CowParent.class, cowParentDao);
    }
    
    public void clear() {
        cowDaoConfig.getIdentityScope().clear();
        cowParentDaoConfig.getIdentityScope().clear();
    }

    public CowDao getCowDao() {
        return cowDao;
    }

    public CowParentDao getCowParentDao() {
        return cowParentDao;
    }

}
