package app.estat.mob.db.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import app.estat.mob.db.entity.Bull;
import app.estat.mob.db.entity.Cow;

import app.estat.mob.db.entity.Mate;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MATE".
*/
public class MateDao extends AbstractDao<Mate, Long> {

    public static final String TABLENAME = "MATE";

    /**
     * Properties of entity Mate.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Date = new Property(1, java.util.Date.class, "date", false, "DATE");
        public final static Property CowId = new Property(2, Long.class, "cowId", false, "COW_ID");
        public final static Property BullId = new Property(3, Long.class, "bullId", false, "BULL_ID");
    }

    private DaoSession daoSession;

    private Query<Mate> bull_MatesQuery;
    private Query<Mate> cow_MatesQuery;

    public MateDao(DaoConfig config) {
        super(config);
    }
    
    public MateDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MATE\" (" + //
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DATE\" INTEGER," + // 1: date
                "\"COW_ID\" INTEGER," + // 2: cowId
                "\"BULL_ID\" INTEGER);"); // 3: bullId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MATE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Mate entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(2, date.getTime());
        }
 
        Long cowId = entity.getCowId();
        if (cowId != null) {
            stmt.bindLong(3, cowId);
        }
 
        Long bullId = entity.getBullId();
        if (bullId != null) {
            stmt.bindLong(4, bullId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Mate entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(2, date.getTime());
        }
 
        Long cowId = entity.getCowId();
        if (cowId != null) {
            stmt.bindLong(3, cowId);
        }
 
        Long bullId = entity.getBullId();
        if (bullId != null) {
            stmt.bindLong(4, bullId);
        }
    }

    @Override
    protected final void attachEntity(Mate entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Mate readEntity(Cursor cursor, int offset) {
        Mate entity = new Mate( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // date
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // cowId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // bullId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Mate entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDate(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setCowId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setBullId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Mate entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Mate entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Mate entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "mates" to-many relationship of Bull. */
    public List<Mate> _queryBull_Mates(Long id) {
        synchronized (this) {
            if (bull_MatesQuery == null) {
                QueryBuilder<Mate> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Id.eq(null));
                bull_MatesQuery = queryBuilder.build();
            }
        }
        Query<Mate> query = bull_MatesQuery.forCurrentThread();
        query.setParameter(0, id);
        return query.list();
    }

    /** Internal query to resolve the "mates" to-many relationship of Cow. */
    public List<Mate> _queryCow_Mates(Long cowId) {
        synchronized (this) {
            if (cow_MatesQuery == null) {
                QueryBuilder<Mate> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.CowId.eq(null));
                cow_MatesQuery = queryBuilder.build();
            }
        }
        Query<Mate> query = cow_MatesQuery.forCurrentThread();
        query.setParameter(0, cowId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCowDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getBullDao().getAllColumns());
            builder.append(" FROM MATE T");
            builder.append(" LEFT JOIN COW T0 ON T.\"COW_ID\"=T0.\"ID\"");
            builder.append(" LEFT JOIN BULL T1 ON T.\"BULL_ID\"=T1.\"ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Mate loadCurrentDeep(Cursor cursor, boolean lock) {
        Mate entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Cow cow = loadCurrentOther(daoSession.getCowDao(), cursor, offset);
        entity.setCow(cow);
        offset += daoSession.getCowDao().getAllColumns().length;

        Bull bull = loadCurrentOther(daoSession.getBullDao(), cursor, offset);
        entity.setBull(bull);

        return entity;    
    }

    public Mate loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Mate> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Mate> list = new ArrayList<Mate>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Mate> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Mate> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
